users:
   title: Пользователи
   fields:
       - {id: name, title: Имя, type: char}
       - {id: lastname, title: Фамилия, type: char}
       - {id: paycheck, title: Зарплата, type: int}

rooms:
   title: Комнаты
   fields:
       - {id: department, title: Отдел, type: char}
       - {id: spots, title: Вместимость, type: int}
